config/routes.rb
Rails.application.routes.draw do
    
  get 'sessions/new'

    get 'solicituds/index', to: "solicituds#index"
    get 'solicituds/edit', to: "solicituds#edit"
    get 'solicituds/show', to: "solicituds#show"
    get 'solicituds/new', to: "solicituds#new"
    
    get 'servicios/index', to: "servicios#index"
    get 'servicios/edit', to: "servicios#edit"
    get 'servicios/show', to: "servicios#show"
    get 'servicios/new', to: "servicios#new"
    
    get 'huespeds/index', to: "huespeds#index"
    get 'huespeds/edit', to: "huespeds#edit"
    get 'huespeds/show', to: "huespeds#show"
    get 'huespeds/new', to: "huespeds#new"
    
    get 'empleados/index', to: "empleados#index"
    get 'empleados/edit', to: "empleados#edit"
    get 'empleados/show', to: "empleados#show"
    get 'empleados/new', to: "empleados#new"
    
    get  'users/new',  to: 'users#new'
    get 'pages/signup', to: "pages#welcome"
    
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
  
    root 'sessions#new'
    
    resources :huespeds
    resources :solicituds
    resources :servicios
    resources :empleados
    resources :users
    
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |nombre, mensaje| %>
    <ul>
      <li> <%= mensaje %> </li>
    </ul>
<%end%>

app/views/layouts/_navbar.html.erb
<header>
 <nav class="navegacion">
   <div class="titulo"><%= link_to "UNHOTEL", current_user %></div> 
   <% if logged_in? %>
        <% if current_user.role == 'Admin' %>
            <%= render "layouts/navbarAdmin" %>
        <% else %><% end %>
        <% if current_user.role == 'Huesped' %>
            <%= render "layouts/navbarHuesped" %>
        <% else %><% end %>
        <% if current_user.role == 'Empleado' %>
            <%= render "layouts/navbarEmpleado" %>
        <% else %>
        <% end %>
    <% else %>
        <%= render "layouts/navbarNoUser" %>
   <% end %>
 
 </nav>
</header>

app/views/layouts/_navbarAdmin.html.erb
<ul class="menu">
     
     <li><a>Huespedes</a>
      
       <ul class="submenu">
         <li><%= link_to "Crear huesped", new_huesped_path %></li>
         <li><%= link_to "Consultar huespedes", huespeds_index_path %></li>
       </ul>
       
     </li>
     <li><a>Empleados</a>
      
       <ul class="submenu">
         <li><%= link_to "Crear empleado", new_empleado_path %></li>
         <li><%= link_to "Consultar empleados", empleados_index_path %></li>
         
       </ul>
       
     </li>
     <li><a>Servicios</a>
     
     
       <ul class="submenu">
         <li><%= link_to "Crear servicio", new_servicio_path %></li>
         <li><%= link_to "Consultar servicios", servicios_index_path %></li>
       </ul>
       
     </li>
    
     
     <li><%= link_to "Log out", logout_path, method: :delete %></a></li>
         
   </ul>

app/views/layouts/_navbarEmpleado.html.erb
<ul class="menu">
     
     <li><a>Huespedes</a>
      
       <ul class="submenu">
         <li><%= link_to "Crear huesped", new_huesped_path %></li>
         <li><%= link_to "Consultar huespedes", huespeds_index_path %></li>
       </ul>
       
     </li>
     
     <li><a>Servicios</a>
     
     
       <ul class="submenu">
         <li><%= link_to "Crear servicio", new_servicio_path %></li>
         <li><%= link_to "Consultar servicios", servicios_index_path %></li>
       </ul>
       
     </li>
     <li><a>Solicitar servicios</a>
     
     
       <ul class="submenu">
         <li><%= link_to "Crear solicitud", new_solicitud_path %></li>
         <li><%= link_to "Consultar solicitudes", solicituds_index_path %></li>
       </ul>
       
     </li>
     
     <li><%= link_to "Log out", logout_path, method: :delete %></a></li>
     
     
        
   </ul>

app/views/layouts/_navbarHuesped.html.erb
<ul class="menu">
    
     <li><a>Solicitar servicios</a>
     
     
       <ul class="submenu">
         <li><%= link_to "Crear solicitud", new_solicitud_path %></li>
         <li><%= link_to "Consultar solicitudes", solicituds_index_path %></li>
       </ul>
       
     </li>   
     
     <li><a>Servicios</a>
     
     
       <ul class="submenu">
         <li><%= link_to "Consultar servicios", servicios_index_path %></li>
       </ul>
       
     </li>
     
     <li><%= link_to "Log out", logout_path, method: :delete %></a></li>
        
   </ul>

app/views/layouts/_navbarNoUser.html.erb
 <ul class="menu">
     
     <li><%= link_to "Log in", login_path %></li>
      <li><%= link_to "Sign up", new_user_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UNHOTEL</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <%= render "layouts/navbar" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
         <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
   
  </body>
</html>